image: Visual Studio 2017
environment:
  matrix:
    - node_version: '8'

install:
- ps: |
    $version = Get-Content "$($env:appveyor_build_folder)\common\SolutionInfo.cs" | %{ $regex = "private const string [\w]+Version = `"([^`"]*)`""; if ($_ -match $regex) { $matches[1] } }
    $env:package_version="$($version).$($env:APPVEYOR_BUILD_NUMBER)"
    Update-AppveyorBuild -Version $env:package_version
    $message = "Building "
    $message += " version " + $env:package_version + " "
    Write-Host $message

    $destdir = Join-Path $env:appveyor_build_folder 'lib'
    $destfile = Join-Path $destdir 'deps.zip'
    Set-Location $destdir
    Invoke-WebRequest "https://ghfvs-installer.github.com/dependencies/deps.zip" -OutFile $destfile
    &'7z' -bb3 x 'deps.zip'

    Set-Location $env:appveyor_build_folder

    nuget restore GitForUnity.sln

assembly_info:
  patch: false
  file: common\SolutionInfo.cs
  assembly_informational_version: "{version}"

configuration: Release
build:
  project: GitForUnity.sln
  verbosity: minimal
test:
  assemblies:
    except:
      - '**\*.TestRunner.dll'
      - '**\TestUtils.dll'
  categories:
    except:
    - DoNotRunOnAppVeyor
on_success:
- ps: |

    # save commit
    Add-Content $commitfile $appveyor_repo_commit

    $packageDir="$($env:appveyor_build_folder)\build\packages"
    $gitpackage="com.unity.version-control.git"
    $gituipackage="com.unity.version-control.git.ui"

    $gitzip="$($env:appveyor_build_folder)\$gitpackage-$($env:package_version).zip"
    $gituizip="$($env:appveyor_build_folder)\$gituipackage-$($env:package_version).zip"

    $sourcedir="$packageDir\$gitpackage"
    Write-Output "Zipping $sourcedir to $gitzip"
    7z a $gitzip $sourcedir

    $sourcedir="$packageDir\$gituipackage"
    Write-Output "Zipping $sourcedir to $gitzip"
    7z a $gituizip $sourcedir

    $sourcedir="$$($env:appveyor_build_folder)\build\Release"
    $dllzip="$($env:appveyor_build_folder)\binaries-$($env:package_version).zip"
    Write-Output "Zipping $sourcedir to $dllzip"
    7z a $dllzip $sourcedir

    Write-Output "Uploading $gitzip"
    Push-AppveyorArtifact $gitzip -DeploymentName gitpackage
    Push-AppveyorArtifact $gituizip -DeploymentName gituipackage
    Push-AppveyorArtifact $dllzip -DeploymentName binaries
on_finish:
- ps: |
    Set-Location $env:appveyor_build_folder
    Get-ChildItem $env:appveyor_build_folder\build\*.log | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName logs }
