build_agent_type: Unity::VM
build_agent_image: core-kaunas/win10-vs2017-dotnetcore:latest
build_agent_flavor: m1.large

upm_agent_type: Unity::VM
upm_agent_image: package-ci/win10:stable
upm_agent_flavor: b1.large

test_platforms:
  - name: win
    type: Unity::VM
    image: package-ci/win10:stable
    flavor: b1.large
#  - name: mac
#    type: Unity::VM::osx
#    image: buildfarm/mac:stable
#    flavor: m1.mac
#  - name: linux
#    type: Unity::VM
#    image: yamato/ubuntu-18.04-dotnet:latest
#    flavor: b1.small

test_editors:
  - version: 2019.2

packages:
  - name: com.unity.git.api
    safename: com_unity_git_api
  - name: com.unity.git.ui
    safename: com_unity_git_ui